package scanner

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/gentleman-programming/argus/internal/system"
)

type ActionType string

const (
	ActionCommand ActionType = "command"
	ActionWrite   ActionType = "write"
	ActionPatch   ActionType = "patch"
)

// ProposedAction representa una acción que el agente quiere realizar.
type ProposedAction struct {
	Type        ActionType
	Command     string
	Path        string
	Content     string
	Description string
	Safe        bool
}

// CommandExecutor gestiona la ejecución de herramientas de seguridad y cambios en el sistema.
type CommandExecutor struct {
	AllowDangerous bool
}

// ValidateAndRun simula la validación humana (HITL).
func (e *CommandExecutor) ValidateAndRun(ctx context.Context, action ProposedAction, validateFunc func(ProposedAction) bool) (string, error) {
	fmt.Printf("\n[AGENT PROPOSAL] %s\n", action.Description)
	if action.Type == ActionCommand {
		fmt.Printf("Command: %s\n", action.Command)
	} else {
		fmt.Printf("File: %s (Type: %s)\n", action.Path, action.Type)
	}

	if validateFunc != nil && !validateFunc(action) {
		return "", fmt.Errorf("action rejected by user")
	}

	switch action.Type {
	case ActionWrite:
		return e.writeFile(action)
	case ActionPatch:
		return e.patchFile(action)
	default:
		return e.runCommand(ctx, action)
	}
}

// ValidateAndRunWithHitl executes actions with HITL validation
func (e *CommandExecutor) ValidateAndRunWithHitl(ctx context.Context, action ProposedAction, hitlValidator system.HitlValidator, currentPhase string) (string, error) {
	fmt.Printf("\n[AGENT PROPOSAL] %s\n", action.Description)
	if action.Type == ActionCommand {
		fmt.Printf("Command: %s\n", action.Command)
	} else {
		fmt.Printf("File: %s (Type: %s)\n", action.Path, action.Type)
	}

	// Convert scanner action to HITL proposal
	hitlAction := system.ProposedAction{
		ID:           "", // Will be generated by validator
		Phase:        currentPhase,
		Action:       string(action.Type),
		Target:       action.Path,
		RiskLevel:    e.assessRiskLevel(action),
		Reason:       action.Description,
		Consequences: e.describeConsequences(action),
	}

	// Propose for HITL approval
	decision, err := hitlValidator.ProposeAction(ctx, hitlAction)
	if err != nil {
		return "", fmt.Errorf("HITL validation failed: %w", err)
	}

	if decision.ApprovedBy == "" {
		return "", fmt.Errorf("action not approved by human")
	}

	fmt.Printf("✅ APPROVED by %s: %s\n", decision.ApprovedBy, decision.Reason)

	// Execute the action
	switch action.Type {
	case ActionWrite:
		return e.writeFile(action)
	case ActionPatch:
		return e.patchFile(action)
	default:
		return e.runCommand(ctx, action)
	}
}

type CommandResult struct {
	Stdout   string
	Stderr   string
	ExitCode int
}

func (e *CommandExecutor) runCommand(ctx context.Context, action ProposedAction) (string, error) {
	fmt.Printf("[EXECUTING] %s...\n", action.Command)

	args := strings.Fields(action.Command)
	if len(args) == 0 {
		return "", fmt.Errorf("empty command")
	}

	cmd := exec.CommandContext(ctx, args[0], args[1:]...)

	var stdout, stderr strings.Builder
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()

	output := stdout.String()
	errOutput := stderr.String()

	if err != nil {
		// Return combined output in the error so the agent can analyze it
		return output, fmt.Errorf("command failed with stderr: %s, error: %w", errOutput, err)
	}

	if errOutput != "" {
		return fmt.Sprintf("STDOUT:\n%s\nSTDERR:\n%s", output, errOutput), nil
	}

	return output, nil
}

func (e *CommandExecutor) writeFile(action ProposedAction) (string, error) {
	fmt.Printf("[WRITING] %s...\n", action.Path)

	if err := os.MkdirAll(filepath.Dir(action.Path), 0755); err != nil {
		return "", err
	}

	if err := os.WriteFile(action.Path, []byte(action.Content), 0644); err != nil {
		return "", err
	}

	return fmt.Sprintf("File %s written successfully", action.Path), nil
}

func (e *CommandExecutor) patchFile(action ProposedAction) (string, error) {
	// Simple patch implementation for MVP (append or simple replace)
	fmt.Printf("[PATCHING] %s...\n", action.Path)

	existing, err := os.ReadFile(action.Path)
	if err != nil {
		return "", err
	}

	// This is a very primitive patch, for real SDD we'd want diff/merge
	updated := string(existing) + "\n" + action.Content

	if err := os.WriteFile(action.Path, []byte(updated), 0644); err != nil {
		return "", err
	}

	return fmt.Sprintf("File %s patched successfully", action.Path), nil
}

// assessRiskLevel evaluates the risk level of an action for HITL approval
func (e *CommandExecutor) assessRiskLevel(action ProposedAction) string {
	// Risk assessment based on action type and content
	switch action.Type {
	case ActionCommand:
		// High risk commands
		if strings.Contains(action.Command, "rm ") ||
			strings.Contains(action.Command, "del ") ||
			strings.Contains(action.Command, "format ") ||
			strings.Contains(action.Command, "shutdown ") ||
			strings.Contains(action.Command, "reboot ") {
			return "CRITICAL"
		}
		// Medium risk commands
		if strings.Contains(action.Command, "chmod ") ||
			strings.Contains(action.Command, "chown ") ||
			strings.Contains(action.Command, "iptables ") ||
			strings.Contains(action.Command, "ufw ") ||
			strings.Contains(action.Command, "firewall") {
			return "HIGH"
		}
		// Low risk commands (scanning, info gathering)
		return "LOW"
	case ActionWrite:
		// Writing files is generally medium risk
		if strings.Contains(action.Path, "/etc/") ||
			strings.Contains(action.Path, "config") ||
			strings.Contains(action.Path, "passwd") {
			return "HIGH"
		}
		return "MEDIUM"
	case ActionPatch:
		// Patching is high risk
		return "HIGH"
	default:
		return "MEDIUM"
	}
}

// describeConsequences describes what could happen if the action is executed
func (e *CommandExecutor) describeConsequences(action ProposedAction) string {
	switch action.Type {
	case ActionCommand:
		if strings.Contains(action.Command, "rm ") {
			return "Could delete files or directories permanently"
		}
		if strings.Contains(action.Command, "chmod ") {
			return "Could change file permissions, potentially exposing sensitive data"
		}
		if strings.Contains(action.Command, "iptables ") {
			return "Could modify firewall rules, affecting network security"
		}
		return "Could execute system command with potential side effects"
	case ActionWrite:
		return "Could create or modify files on the system"
	case ActionPatch:
		return "Could modify existing files, potentially breaking functionality"
	default:
		return "Could perform system modifications"
	}
}
